from app.models.alumno import Alumno
from app.models.ciclo_escolar import CicloEscolar
from app.models.credencial import Credencial
from app.models.grupo import Grupo
from app.models.justificacion import Justificacion
from app.models.profesor import Profesor
from app.models.registro_acceso import RegistroAcceso
from app.models.reporte import Reporte
from app.models.retardo import Retardo
from app.models.rol import Rol
from app.models.usuario import Usuario
