from app.models.alumno import Alumno
from app.models.ciclo_escolar import CicloEscolar
from app.models.configuracion_asistencia import ConfiguracionAsistencia
from app.models.configuracion_general import ConfiguracionGeneral
from app.models.credencial import Credencial
from app.models.grupo import Grupo
from app.models.horario import Horario
from app.models.incidencia import Incidencia
from app.models.inscripcion import Inscripcion
from app.models.justificacion import Justificacion
from app.models.permiso import Permiso
from app.models.profesor import Profesor
from app.models.registro_acceso import RegistroAcceso
from app.models.reposicion import Reposicion
from app.models.reporte import Reporte
from app.models.reporte_programado import ReporteProgramado
from app.models.retardo import Retardo
from app.models.rol import Rol
from app.models.usuario import Usuario
